### ISSUE TITLE
레시피 컴포넌트 개선

### ISSUE THREAD

**Issue by hae-on** [fun-eat/funeat-client#81]
## 어떤 기능을 구현하나요?

<img width="753" alt="스크린샷 2024-04-10 오후 9 50 38" src="https://github.com/fun-eat/funeat-client/assets/80464961/6f7ce8fe-8a08-4d6f-bd13-6600cc87847b">

현재 레시피 컴포넌트를 보면, 위와 같은 4가지로 구분할 수 있습니다.
이를 컴파운드 패턴으로 변경하려고 합니다.
일단 만들어두고 교체 작업도 제가 진행하겠습니다.

## 일정

- 추정 시간 2시간

**Comment by Leejin-Yang** [comment]
와 생각보다 배리에이션이 많네요
상품 상세에서 제가 props로 수정했는데 컴파운드 패턴으로 수정하는 걸까요?

**Comment by hae-on** [comment]
넵! 컴파운드 패턴으로 수정하고 있습니다.
상품 상세에서 변경 있었으면 나중에 그거 머지되면 또 한번에 땡겨서 제가 바꿔야 할 듯???
